package com.memcache.gateway.kv;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicInteger;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;

/**
 * Caps how many writes one client may make per hour.
 *
 * WHY THE CLIENT IP AND NOT THE SESSION HEADER
 *
 * X-Beedb-Session is generated by the browser. Anyone rate-limited on it simply sends
 * a fresh random value with the next request -- you would have limited nobody and
 * added a cache lookup. A limit is only ever as good as the identity it is keyed on,
 * and the only identity here the client cannot trivially change is the source
 * address.
 *
 * WHICH ADDRESS, THOUGH
 *
 * in production the path is browser -> Cloudflare -> nginx -> gateway, so by the time
 * Spring sees the request the remote address is NGINX. Every visitor would look like
 * one client and the first ten writes would lock out the world. The real address
 * arrives in a header (CF-Connecting-IP, X-Forwarded-For) -- and those are exactly as
 * forgeable as the session header unless they are only trusted when the connection
 * came from our own proxy. That is what server.forward-headers-strategy plus an nginx
 * that actually sets them is for; see the deploy notes. Until then this sees the real
 * address because nothing sits in front.
 *
 * WHY OPERATIONS AND NOT DISTINCT KEYS
 *
 * "ten keys per hour" would bound storage, which is already bounded by the registry's
 * maximumSize and its TTL. It would not bound LOAD: hammering a single key in a loop
 * stays within a distinct-key budget forever, while still costing a full Raft round
 * trip every time. Writes are what this is protecting, so writes are what it counts.
 *
 * WHAT THIS IS NOT
 *
 * A FIXED window, not a sliding one. Ten writes at 59:59 and ten more at 60:01 gets
 * twenty through in two seconds. Fine for a demo, and stated here rather than
 * discovered later.
 *
 * nor does it stop a distributed flood, or anyone with a handful of addresses. It
 * raises the cost of abuse; it does not prevent it. The volumetric floor belongs in
 * nginx (limit_req, limit_conn), which can reject a flood before it costs us a
 * thread -- something this class cannot do, because by the time it runs we already
 * have one.
 */
public class WriteRateLimiter {

    private final Cache<String, AtomicInteger> writesPerClient;
    private final int maxWritesPerHour;

    public WriteRateLimiter(int maxWritesPerHour) {
        this.maxWritesPerHour = maxWritesPerHour;
        this.writesPerClient = Caffeine.newBuilder()
                .expireAfterWrite(Duration.ofHours(1))
                // Bound the number of distinct clients tracked, or the limiter
                // becomes its own memory-exhaustion vector: one request per forged
                // source address is all it would take.
                .maximumSize(10_000)
                .build();
    }

    /**
     * Count one write against this client and say whether it is allowed.
     *
     * Counting happens whether or not the write is permitted -- a client that keeps
     * hammering after being refused does not get a fresh budget by being refused.
     *
     * @return true if the write may proceed
     */
    public boolean tryAcquire(String clientId) {
        AtomicInteger count = writesPerClient.get(clientId, k -> new AtomicInteger());
        return count.incrementAndGet() <= maxWritesPerHour;
    }

    /** Writes still available to this client in the current window. Never negative. */
    public int remaining(String clientId) {
        AtomicInteger count = writesPerClient.getIfPresent(clientId);
        int used = count == null ? 0 : count.get();
        return Math.max(0, maxWritesPerHour - used);
    }

    public long resetInSeconds(String clientId) {
        return writesPerClient.policy().expireAfterWrite()
                .flatMap(window -> window.ageOf(clientId)
                        .map(age -> window.getExpiresAfter().minus(age)))
                .map(left -> Math.max(0L, (left.toMillis() + 999) / 1000))
                .orElse(0L);
    }

    public int maxWritesPerHour() {
        return maxWritesPerHour;
    }
}
